sudo: required
services:
    - docker

before_install:
    - docker build -t idlikesometea/react-test -f .client/Dockerfile.dev ./client

script:
    - docker run -e CI=true idlikesometea/react-test npm test

after_success:
    - docker build -t idlikesometea/multi-client ./client
    - docker build -t idlikesometea/multi-nginx ./nginx
    - docker build -t idlikesometea/multi-server ./server
    - docker build -t idlikesometea/multi-worker ./worker